version: '3.8'
services:
  #  mysql 8
  mysql:
    image: 'mysql:8'
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=oauth2_test
      - MYSQL_USER=rex
      - MYSQL_PASSWORD=111111
  #  redis 7
  redis:
    image: 'redis:7'
    container_name: redis
    ports:
      - '6379:6379'