spring:
  datasource:
    username: rex
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_test?useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org:
    springframework:
    security: debug
